library identifier: 'Jenkins_Pipeline_Shared_Libs@main',retriever: modernSCM([$class: 'gitSCMSource',remote:'https://github.com/alazarbeyenenew2/jenkins.git'])
pipeline {
    agent any 

  parameters{
      booleanParam(name:"RELEASE",defaultValue:false, description:"replease to production")
  }

    environment {
        RELEASE = "2.0"
    }

    stages {
    
        stage('clone') {
        agent any 
        environment{
            LOG_LEVEL = "INFO"
        }
        
            steps {
                sh '''
                    echo "clone release version ${BUILD_ID}  and log level ${LOG_LEVEL}"
                '''
            }
        }

   stage ("build"){
    steps{
        build job: 'building app', wait: true    
        }
   }

        stage('deploy') {
            steps {
                deploy()
            }
        }

        stage("test"){
          steps{
              dir("./test"){
                sh ''' cat test.txt  '''
          }  
          }  
        }

        stage("release to production"){
            when{
                expression {return params.RELEASE}
            }
            steps{
                archiveArtifacts("**/test/*.txt")
            }
        }

        stage ('Deploy'){
             input{
                message "deploy"
                ok "do it "
                parameters{
                    string(name:"TARGET_ENV",defaultValue:"PROD",description:"target environment")
                }
             }

             steps{
                 sh ''' 
                 echo "deploying  to ${TARGET_ENV} release version ${RELEASE}"
                 ls
                   '''
             }
        }
     
    }

    post{
        always {
            cleanWs()
        }
    }
}

void deploy (){
    sh '''  echo "building application " '''
}