pipeline {
    agent any 

    environment {
        RELEASE = "2.0"
    }

    stages {
    
        stage('clone') {
        agent any 
        environment{
            LOG_LEVEL = "INFO"
        }
        
            steps {
                sh '''
                    echo "clone release version ${BUILD_ID}  and log level ${LOG_LEVEL}"
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                    echo "building"
                '''
            }
        }

        stage("test"){
          steps{
              dir("./test"){
                sh ''' cat test.txt  '''
          }  
          }  
        }

        stage ('Deploy'){
             input{
                message "deploy"
                ok "do it "
                parameters{
                    string(name:"TARGET_ENV",defaultValue:"PROD",description:"target environment")
                }
             }

             steps{
                 sh ''' 
                 echo "deploying  to ${TARGET_ENV} release version ${RELEASE}"
                 ls
                   '''
             }
        }
     
    }

    post{
        always {
            cleanWs()
        }
    }
}

