pipeline {
    agent any 

    environment {
        TEST_ENV = "test env"
    }

    stages {
        stage('Clone') {
            steps {
                sh '''
                    echo "cloning repo"
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                    echo "building"
                '''
            }
        }
    }
}

